[project]
name = "count-push-up"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lap>=0.5.12",
    "opencv-contrib-python>=4.11.0.86",
    "shapely>=2.1.1",
    "ultralytics>=8.3.143",
]
